### ISSUE TITLE
Add PyPy2 and PyPy3 builds on Travis

### ISSUE THREAD

**Issue by ghackebeil** [Pyomo/pyomo#447]
...once expr_dev is merged. Also update README about support for PyPy once we confirm Travis tests pass.

**Comment by ghackebeil** [comment]
@whart222, @jsiirola: Here are some action items you can take that will allow me to start modifying the Travis builds to use our own custom docker images.

- Create an account on Docker Hub.
- Optionally create a Pyomo organization on Docker Hub
- Create an empty public Docker Hub repository with a name like pyomo-test-builds
- Create a public GitHub repo with a name like Pyomo/docker-builds (or some other name you prefer) and add a .travis.yml file, like what is below, that contains the travis-encrypted Docker Hub login credentials of whoever owns the Docker Hub repo.
```
sudo: required
cache: false
language: python
services:
- docker
env:
  global:
  - secure: ...
  - secure: ...
script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
```
- Give me push access to master on the GitHub repo

Ping me once that is ready, and I'll starting working on it in the next few weeks.
